repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: db7346d375eda68a0174f2c057dd97f2fbffe030 # frozen 4.2.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace

  - repo: https://github.com/psf/black
    rev: ae2c0758c9e61a385df9700dc9c231bf54887041 # frozen 22.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/isort
    rev: c5e8fa75dda5f764d20f66a215d71c21cfa198e1 # frozen 5.10.1
    hooks:
      - id: isort
        name: isort (python)
        args: ["--profile", "black"]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: e1ba0b6ec1deaea4243d9469af65131207a24e53 # frozen 0.960
    hooks:
      - id: mypy
